### PR TITLE
Fixes #69 Fix name errors and layout differences among the gen'd apps

### LINKED ISSUE #69: React code to get name contains an error
>         <h1>Hello, <span id="heading-name">{ person.name() ? person.name() : 'Nameless Person' }</span>!</h1>

This code never resolves properly.  Always comes back as nameless even if the username is available.

### PR DESCRIPTION
**Pull request by moxiegirl**
Ensure the proper profile photo and blockstack id appears

- [x] React
- [x]  Webpack
- [x] Vue

Make sure no CORS issue when running locally

- [x] React
- [x]  Webpack
- [x] Vue

Both Webpack and Vue have same header as React

- [x]  Webpack
- [x] Vue

Signed-off-by: Mary Anthony <mary@blockstack.com>

### CODE REVIEW

File: react/templates/src/Profile.js [hunk 1]
```diff
@@ -23,14 +23,15 @@ export default class Profile extends Component {
...
+    const username = this.props.userSession.loadUserData().username;
     const { person } = this.state;
     return (
       !userSession.isSignInPending() ?
       <div className="panel-welcome" id="section-2">
         <div className="avatar-section">
           <img src={ person.avatarUrl() ? person.avatarUrl() : avatarFallbackImage } className="img-rounded avatar" id="avatar-image" alt=""/>
         </div>
-        <h1>Hello, <span id="heading-name">{ person.name() ? person.name() : 'Nameless Person' }</span>!</h1>
+        <h1>Hello, <span id="heading-name">{ person.name ? username : 'Nameless Person' }</span>!</h1>
```
Comment (zone117x) [inline react/templates/src/Profile.js]: I think this should be:
```js
person.name() || username || 'Nameless Person'
```
Otherwise it will never show the human entered name

Comment (moxiegirl) [reply react/templates/src/Profile.js]: It does with my change, at least with my tests.  I'll give your solution a try tho.

**Review by zone117x — APPROVED** [review]

File: vue/templates/_package.json [hunk 2]
```diff
@@ -1,5 +1,5 @@
 {
-  "name": "bs-todo",
+  "name": "hello-blockstack",
   "version": "6.0.1",
   "description": "A decentralized Todo app built on Blockstack",
   "author": "Michael Stivala <michaelstivala@me.com> (https://michaelstivala.com/)",
```
Comment (yknl) [inline vue/templates/_package.json]: We should probably change the author line as well

**Review by yknl — APPROVED** [review]

File: vue/templates/_package.json (hunk 2 above)
Comment (moxiegirl) [reply vue/templates/_package.json]: done.
